workflows:
  ios-web-app:
    name: Build iOS Web App
    max_build_duration: 15
    environment:
      vars:
        NODE_VERSION: "20.10.0"
      node: $NODE_VERSION
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build || echo "no build script defined"
      - name: Convert to iOS using Capacitor
        script: |
          npm install --global @capacitor/cli
          npx cap init schedulepro com.yourcompany.schedulepro --web-dir=dist
          npx cap add ios
          npx cap copy ios
      - name: Build .ipa file
        script: |
          xcodebuild -project ios/App/App.xcodeproj \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/App.xcarchive archive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build
    artifacts:
      - ios/App/App.xcodeproj/project.pbxproj
      - $CM_BUILD_DIR/build/*.ipa
      - $CM_BUILD_DIR/build/**/*

